### ISSUE TITLE
Support organization package

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/preview#10]
Current API doesn't support package with an organization namespace like `@nodesecure/`. In case of an error the page will load indefinitely without informing the user of an error.

![image](https://user-images.githubusercontent.com/4438263/147777351-8205937e-59cd-472e-b994-e90b9f7f1c85.png)

I guess this is because the `/` should be escaped for `%2F` in `index.tsx`:

```ts
const res = await fetch(`/api/scanner/${pkgName.replace("/", "%2F")}`);
```

For example in the CLI:
- https://github.com/ES-Community/nsecure/blob/master/public/js/utils.js#L217
- https://github.com/ES-Community/nsecure/blob/master/src/http-server/bundle.js#L9

**Comment by tony-go** [comment]
Nice catch! 👏

**Comment by viterb-c** [comment]
Hello, 

I have been working on this issue and the example '@nodesecure/scanner' raises another issue. 
The slash '/' create a sub-view in next.js router that doesn't exist.
A solution is to apply the same replace in router.push. 
We have http://localhost:3000/scan/@nodesecure%2Fscanner instead of http://localhost:3000/scan/@nodesecure/scanner

Do you want to open a new issue for this problem or i can fix it in the same PR ?

**Comment by tony-go** [comment]
Hey @viterb-c 👋 

Thanks a lot for this. 🙏🏼

Yeap go ahead in your PR :)
